-- Create users table in Supabase to replace MySQL users
CREATE TABLE IF NOT EXISTS public.users (
  id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_cliente TEXT NOT NULL UNIQUE,
  senha_cliente TEXT NOT NULL,
  has_uploaded BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS (functions will use service role)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Timestamp trigger
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_updated_at ON public.users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at();