// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drmrxhbwvlpigljimayp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybXJ4aGJ3dmxwaWdsamltYXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzM4MjksImV4cCI6MjA3MDUwOTgyOX0.QdiRh051L17cwNaf_9-31E-L8Y8hXxi8SJBoCFYRpUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});